/* The following code was generated by JFlex 1.6.0 */

import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>lexico.flex</tt>
 */
public class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMENTARIO = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\36\1\2\1\51\1\51\1\35\22\0\1\36\1\42\1\1"+
    "\2\0\1\50\1\43\1\3\1\52\1\52\1\46\1\45\1\52\1\34"+
    "\1\32\1\47\12\31\1\52\1\52\1\37\1\40\1\41\2\0\4\4"+
    "\1\33\25\4\1\52\1\0\1\52\1\0\1\30\1\0\1\13\1\21"+
    "\1\14\1\17\1\22\1\10\1\4\1\15\1\5\1\4\1\26\1\11"+
    "\1\4\1\6\1\12\1\27\1\4\1\16\1\25\1\7\1\20\1\23"+
    "\1\24\3\4\1\52\1\44\1\52\7\0\1\51\u1f93\0\1\52\16\0"+
    "\1\51\1\51\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\1\14\3\1\4\1\2\2\1"+
    "\4\2\2\1\5\2\1\1\2\0\2\3\1\5\5\3"+
    "\1\6\11\3\1\7\2\0\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\3"+
    "\1\33\15\3\1\34\1\0\1\3\1\35\1\36\4\3"+
    "\1\37\1\40\2\3\1\41\2\3\2\0\1\42\3\3"+
    "\1\43\1\44\2\3\1\45\1\0\1\46\1\47\1\3"+
    "\1\50\1\51\1\34\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\u012d"+
    "\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a\0\u0285"+
    "\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387\0\u03b2\0\u03dd"+
    "\0\u0408\0\u0433\0\u045e\0\u0489\0\u04b4\0\u04df\0\u050a\0\u0535"+
    "\0\126\0\u0560\0\u058b\0\u05b6\0\u05e1\0\u060c\0\u0102\0\u0637"+
    "\0\u0662\0\u068d\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u0764\0\u078f"+
    "\0\u07ba\0\u07e5\0\u0810\0\u083b\0\u0866\0\u0891\0\126\0\u08bc"+
    "\0\u08e7\0\126\0\126\0\126\0\126\0\126\0\126\0\126"+
    "\0\126\0\126\0\126\0\126\0\126\0\126\0\u0912\0\126"+
    "\0\126\0\126\0\126\0\u0102\0\u093d\0\u0102\0\u0968\0\u0993"+
    "\0\u09be\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb"+
    "\0\u0b16\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2\0\u0bed\0\u0102\0\u0102"+
    "\0\u0c18\0\u0c43\0\u0c6e\0\u0c99\0\u0102\0\u0102\0\u0cc4\0\u0cef"+
    "\0\u0102\0\u0d1a\0\u0d45\0\u0d70\0\u0d9b\0\u0102\0\u0dc6\0\u0df1"+
    "\0\u0e1c\0\u0102\0\u0102\0\u0e47\0\u0e72\0\u0102\0\u0e9d\0\u0102"+
    "\0\u0102\0\u0ec8\0\u0102\0\u0102\0\u0ef3\0\u0102";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\2\7\1\11"+
    "\3\7\1\12\1\7\1\13\1\14\1\7\1\15\1\16"+
    "\1\17\1\20\1\21\1\7\1\22\1\7\1\23\1\3"+
    "\1\7\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\0\1\41"+
    "\2\3\1\5\32\3\2\26\7\3\1\42\4\3\53\0"+
    "\1\43\2\0\50\43\2\0\1\5\54\0\24\44\3\0"+
    "\1\44\23\0\25\7\1\45\1\0\1\7\23\0\2\7"+
    "\1\46\1\7\1\47\20\7\1\45\1\0\1\7\23\0"+
    "\5\7\1\50\1\51\16\7\1\45\1\0\1\7\23\0"+
    "\7\7\1\52\1\7\1\53\13\7\1\45\1\0\1\7"+
    "\23\0\16\7\1\54\6\7\1\45\1\0\1\7\23\0"+
    "\6\7\1\55\7\7\1\56\6\7\1\45\1\0\1\7"+
    "\23\0\12\7\1\57\12\7\1\45\1\0\1\7\23\0"+
    "\5\7\1\60\17\7\1\45\1\0\1\7\23\0\6\7"+
    "\1\61\16\7\1\45\1\0\1\7\23\0\11\7\1\62"+
    "\13\7\1\45\1\0\1\7\23\0\3\7\1\63\4\7"+
    "\1\64\7\7\1\65\4\7\1\45\1\0\1\7\23\0"+
    "\12\7\1\66\12\7\1\45\1\0\1\7\27\0\1\67"+
    "\20\0\1\23\1\70\1\71\53\0\1\72\3\0\1\73"+
    "\14\0\1\3\32\0\2\26\51\0\2\26\54\0\1\74"+
    "\52\0\1\75\52\0\1\76\52\0\1\77\55\0\1\100"+
    "\53\0\1\101\46\0\1\102\4\0\1\103\45\0\1\104"+
    "\52\0\1\105\5\0\1\106\1\107\43\0\1\110\61\0"+
    "\1\111\3\0\1\43\1\112\1\0\50\43\3\0\1\113"+
    "\100\0\1\45\25\0\3\7\1\114\21\7\1\45\1\0"+
    "\1\7\23\0\6\7\1\115\16\7\1\45\1\0\1\7"+
    "\23\0\12\7\1\116\12\7\1\45\1\0\1\7\23\0"+
    "\21\7\1\117\3\7\1\45\1\0\1\7\23\0\7\7"+
    "\1\120\15\7\1\45\1\0\1\7\23\0\3\7\1\121"+
    "\21\7\1\45\1\0\1\7\23\0\14\7\1\122\10\7"+
    "\1\45\1\0\1\7\23\0\4\7\1\123\20\7\1\45"+
    "\1\0\1\7\23\0\16\7\1\124\6\7\1\45\1\0"+
    "\1\7\23\0\21\7\1\125\3\7\1\45\1\0\1\7"+
    "\23\0\1\7\1\126\23\7\1\45\1\0\1\7\23\0"+
    "\1\7\1\127\23\7\1\45\1\0\1\7\23\0\12\7"+
    "\1\130\12\7\1\45\1\0\1\7\23\0\7\7\1\131"+
    "\15\7\1\45\1\0\1\7\23\0\1\7\1\132\23\7"+
    "\1\45\1\0\1\7\23\0\1\7\1\133\23\7\1\45"+
    "\1\0\1\7\50\0\1\134\55\0\1\135\10\0\1\135"+
    "\5\0\2\107\1\0\32\107\1\0\13\107\1\0\1\107"+
    "\4\0\7\7\1\136\15\7\1\45\1\0\1\7\23\0"+
    "\16\7\1\137\6\7\1\45\1\0\1\7\23\0\12\7"+
    "\1\140\12\7\1\45\1\0\1\7\23\0\14\7\1\141"+
    "\10\7\1\45\1\0\1\7\23\0\15\7\1\142\7\7"+
    "\1\45\1\0\1\7\23\0\7\7\1\143\15\7\1\45"+
    "\1\0\1\7\23\0\7\7\1\144\15\7\1\45\1\0"+
    "\1\7\23\0\16\7\1\145\6\7\1\45\1\0\1\7"+
    "\23\0\13\7\1\146\11\7\1\45\1\0\1\7\23\0"+
    "\5\7\1\147\17\7\1\45\1\0\1\7\23\0\14\7"+
    "\1\150\10\7\1\45\1\0\1\7\23\0\2\7\1\151"+
    "\22\7\1\45\1\0\1\7\23\0\3\7\1\152\21\7"+
    "\1\45\1\0\1\7\23\0\2\7\1\153\22\7\1\45"+
    "\1\0\1\7\27\0\1\67\20\0\1\134\1\0\1\154"+
    "\50\0\1\155\25\0\3\7\1\156\21\7\1\45\1\0"+
    "\1\7\23\0\12\7\1\157\12\7\1\45\1\0\1\7"+
    "\23\0\5\7\1\160\17\7\1\45\1\0\1\7\23\0"+
    "\14\7\1\161\10\7\1\45\1\0\1\7\23\0\22\7"+
    "\1\162\2\7\1\45\1\0\1\7\23\0\16\7\1\163"+
    "\6\7\1\45\1\0\1\7\23\0\10\7\1\164\14\7"+
    "\1\45\1\0\1\7\23\0\10\7\1\165\14\7\1\45"+
    "\1\0\1\7\23\0\3\7\1\166\21\7\1\45\1\0"+
    "\1\7\53\0\1\167\10\0\1\167\15\0\1\67\20\0"+
    "\1\155\25\0\2\7\1\170\22\7\1\45\1\0\1\7"+
    "\23\0\16\7\1\171\6\7\1\45\1\0\1\7\23\0"+
    "\5\7\1\172\17\7\1\45\1\0\1\7\23\0\3\7"+
    "\1\173\21\7\1\45\1\0\1\7\23\0\11\7\1\174"+
    "\13\7\1\45\1\0\1\7\50\0\1\175\25\0\3\7"+
    "\1\176\21\7\1\45\1\0\1\7\27\0\1\67\20\0"+
    "\1\175\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3870];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\35\1\1\11\1\1\2\0\22\1\1\11"+
    "\2\0\15\11\1\1\4\11\21\1\1\0\16\1\2\0"+
    "\11\1\1\0\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	boolean coment = false;	
	
        /* Metodos que ayudan a procesar el retorno de los tokens al
	   metodo next_token*/

	/*private Symbol tokenNuevo(int type, Object lex){
		int linea = yyline + 1;
		System.out.println("token : "+ lex + "," + type);
                return new Symbol(type,yyline, yycolumn, lex);
	}
	
	private Symbol tokenNuevo(int type){
                return tokenNuevpo(type, yytext());
	}*/

	private Parser yyparser;
	
	public Yylex(Reader r, Parser yyparser){
		this(r);
		this.yyparser = yyparser;
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 178) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { 
          }
        case 43: break;
        case 2: 
          { return (int) yycharat(0);
          }
        case 44: break;
        case 3: 
          { yyparser.yylval = new ParserVal(yytext()); return Parser.ID;
          }
        case 45: break;
        case 4: 
          { yyparser.yylval = new ParserVal(Integer.parseInt(yytext())); return Parser.ENTERO;
          }
        case 46: break;
        case 5: 
          { return Parser.IF;
          }
        case 47: break;
        case 6: 
          { return Parser.DO;
          }
        case 48: break;
        case 7: 
          { yyparser.yylval = new ParserVal(Double.parseDouble(yytext())); return Parser.REAL;
          }
        case 49: break;
        case 8: 
          { return Parser.DEC;
          }
        case 50: break;
        case 9: 
          { return Parser.MENOSIGUAL;
          }
        case 51: break;
        case 10: 
          { return Parser.MENIGU;
          }
        case 52: break;
        case 11: 
          { return Parser.IGUAL;
          }
        case 53: break;
        case 12: 
          { return Parser.MAYIGU;
          }
        case 54: break;
        case 13: 
          { return Parser.DIF;
          }
        case 55: break;
        case 14: 
          { return Parser.AND;
          }
        case 56: break;
        case 15: 
          { return Parser.OR;
          }
        case 57: break;
        case 16: 
          { return Parser.MASIGUAL;
          }
        case 58: break;
        case 17: 
          { return Parser.INC;
          }
        case 59: break;
        case 18: 
          { return Parser.MULTIGUAL;
          }
        case 60: break;
        case 19: 
          { return Parser.DIVIGUAL;
          }
        case 61: break;
        case 20: 
          { yybegin(COMENTARIO); coment= true;
          }
        case 62: break;
        case 21: 
          { System.out.println("Encontro un comentario");
          }
        case 63: break;
        case 22: 
          { return Parser.MODUIGUAL;
          }
        case 64: break;
        case 23: 
          { System.out.println("Encontro un comentario"); yybegin(YYINITIAL); coment=false;
          }
        case 65: break;
        case 24: 
          { yyparser.yylval = new ParserVal(yytext());return Parser.CADENA;
          }
        case 66: break;
        case 25: 
          { yyparser.yylval = new ParserVal(yytext()); return Parser.CARACTER;
          }
        case 67: break;
        case 26: 
          { return Parser.INT;
          }
        case 68: break;
        case 27: 
          { return Parser.FOR;
          }
        case 69: break;
        case 28: 
          { yyparser.yylval = new ParserVal(Double.parseDouble(yytext())); return Parser.DOBLE;
          }
        case 70: break;
        case 29: 
          { return Parser.CASE;
          }
        case 71: break;
        case 30: 
          { return Parser.CHAR;
          }
        case 72: break;
        case 31: 
          { return Parser.ELSE;
          }
        case 73: break;
        case 32: 
          { return Parser.VOID;
          }
        case 74: break;
        case 33: 
          { return Parser.SCAN;
          }
        case 75: break;
        case 34: 
          { return Parser.FLOAT;
          }
        case 76: break;
        case 35: 
          { return Parser.BREAK;
          }
        case 77: break;
        case 36: 
          { return Parser.WHILE;
          }
        case 78: break;
        case 37: 
          { return Parser.PRINT;
          }
        case 79: break;
        case 38: 
          { return Parser.RETURN;
          }
        case 80: break;
        case 39: 
          { return Parser.DOUBLE;
          }
        case 81: break;
        case 40: 
          { return Parser.STRUCT;
          }
        case 82: break;
        case 41: 
          { return Parser.SWITCH;
          }
        case 83: break;
        case 42: 
          { return Parser.DEFAULT;
          }
        case 84: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 
	// Al llegar al fin de archivo validamos que no se haya quedado un comentario
	// de varias lineas sin cerrar
	if(coment){
		System.out.println("ERROR LEXICO: no se ha cerrado un comentario");
		coment = false;
	}
	System.out.println("Análisis Léxico completo");
    return YYEOF;

	

 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
